version: '3'

services:
  epicmafia-api:
    build: ./epicmafia-api
    volumes:
      - ./epicmafia-api:/usr/src/app
    ports:
      - 5001:80

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - 5000:80
    depends_on:
      - epicmafia-api
